### ISSUE TITLE
capture screenshot for particular div

### ISSUE THREAD

**Issue by swapHash** [fayeed/use-screenshot#1]
how to capture screenshot for particular div in react

**Comment by fayeed** [comment]
You need to pass the ref of the element you want to capture a screenshot of

`useScreenshot({ref: ref});`

**Comment by philohelp** [comment]
It is very strange: sometimes it takes the ref and everything works correctly, then I change totally unrelated things in the site and it won't take the ref anymore (and shoots the entire page). Spent 2 hours on this one and I really can't find what is going on.

**Comment by yaqshank92** [comment]
well, I am trying to take a screenshot of a particular div/component that contains a layered/masked image using usescreenshot in react, though I am only getting the color of the topmost image that i am dynamically changing using color picker, i am unable to find a direction how to resolve?
const generateImgRef = useRef(null);
<button onClick={() => exportAsImage(generateImgRef.current, "test")}></button>
<GenerateMyImage layers={layers} generateImgRef={generateImgRef}/>
